
{{- if .Values.cds.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tiledesk.fullname" . }}-cds
  labels: {{ include "tiledesk.labels" . | nindent 4 }}
    app.kubernetes.io/component: design-studio
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels: {{ include "tiledesk.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: design-studio
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:       
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels: {{ include "tiledesk.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: design-studio
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tiledesk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.cds.image.repository }}:{{ .Values.cds.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.cds.image.pullPolicy }}
          env:  
            - name: FEATURES_TOKEN  
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FEATURES_TOKEN
            - name: SERVER_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: SERVER_BASE_URL
            - name: BRAND_SRC
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: BRAND_SRC
            - name: REMOTE_JS_SRC
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: REMOTE_JS_SRC
            - name: WIDGET_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: WIDGET_LOCATION
            - name: DASHBOARD_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: DASHBOARD_URL
            - name: WHATSAPP_TEMPLATES_BASE_URL
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: WHATSAPP_TEMPLATES_BASE_URL
            - name: WS_URL_RELATIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: WS_URL_RELATIVE
            - name: UPLOAD_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: UPLOAD_ENGINE
            - name: API_BASEIMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: API_BASEIMAGE_URL
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: LOG_LEVEL
            - name: CDS_STORAGE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CDS_STORAGE_PREFIX
            - name: PHONE_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: PHONE_NUMBER
            - name: FIREBASE_APIKEY 
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FIREBASE_APIKEY
            - name: FIREBASE_AUTHDOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FIREBASE_AUTHDOMAIN
            - name: FIREBASE_DATABASEURL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FIREBASE_DATABASEURL
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FIREBASE_PROJECT_ID
            - name: FIREBASE_STORAGEBUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FIREBASE_STORAGEBUCKET
            - name: FIREBASE_MESSAGINGSENDERID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FIREBASE_MESSAGINGSENDERID
            - name: FIREBASE_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FIREBASE_APP_ID
            - name: FIREBASE_VAPID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FIREBASE_VAPID                
          ports:
            - name: cds-http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: cds-http
          readinessProbe:
            httpGet:
              path: /
              port: cds-http
          resources:
            {{- toYaml .Values.cds.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
