{{- if and (.Values.c21httpsrv.enabled) (eq .Values.CHAT21_ENGINE "mqtt") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tiledesk.fullname" . }}-c21httpsrv
  labels: {{ include "tiledesk.labels" . | nindent 4 }}
    app.kubernetes.io/component: c21httpsrv
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.chatReplicaCount }}
{{- end }}
  selector:
    matchLabels: {{ include "tiledesk.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: c21httpsrv
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels: {{ include "tiledesk.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: c21httpsrv
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tiledesk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.c21httpsrv.image.repository }}:{{ .Values.c21httpsrv.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.c21httpsrv.image.pullPolicy }}
          env:                                             
            - name: JWT_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CHAT21_JWT_SECRET                                                
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CHAT21_MONGODB_URI
            - name: RABBITMQ_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CHAT21_HTTPSRV_RABBITMQ_URI       
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "tiledesk.fullname" . }}
                  key: firebase-privatekey
            - name: FIREBASE_CLIENT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FIREBASE_CLIENT_EMAIL
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FIREBASE_PROJECT_ID      
            - name: FIREBASE_APIKEY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FIREBASE_APIKEY
            - name: PUSH_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: PUSH_ENABLED
            - name: PUSH_WH_CHAT21_API_ADMIN_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: PUSH_WH_CHAT21_API_ADMIN_TOKEN
            - name: PUSH_WH_NOTIFY_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: PUSH_WH_NOTIFY_URL              
            - name: PUSH_WH_WEBHOOK_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: PUSH_WH_WEBHOOK_TOKEN
            - name: WEB_CLICK_ACTION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: WEB_CLICK_ACTION
            - name: MOBILE_CLICK_ACTION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: MOBILE_CLICK_ACTION
            - name: CONTACTS_LOOKUP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CONTACTS_LOOKUP_ENDPOINT 
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: LOG_LEVEL
            - name: CHAT21HTTP_CACHE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CHAT21HTTP_CACHE_ENABLED
            - name: CHAT21HTTP_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CHAT21HTTP_REDIS_HOST
            - name: CHAT21HTTP_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CHAT21HTTP_REDIS_PORT                                                                                     
          ports:
            - name: c21httpsrv-http
              containerPort: 8004
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: c21httpsrv-http
          readinessProbe:
            httpGet:
              path: /
              port: c21httpsrv-http
          resources:
            {{- toYaml .Values.c21httpsrv.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
