{{- if .Values.ingress.enabled -}}
{{- $fullName := include "tiledesk.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-proxy-nginx
  labels:
    {{- include "tiledesk.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    
    {{- if .Values.ingress.hosts.hostip.enabled }}
    - host: {{ .Values.ingress.hosts.hostip.name | quote }}
      http:
        paths:
          {{- range .Values.ingress.hosts.hostip.paths }}
            {{- if or (not (hasKey . "enabled")) (eq .enabled true) }}
          - path: {{ .path }}
            pathType: ImplementationSpecific          
            backend:
              service:
                name: {{ $fullName }}-{{ .service }}
                port:
                  number: {{- if .servicePort }} {{ .servicePort }}{{- else }} {{ $svcPort }}{{- end }}                       
            {{- end }}
          {{- end }}
    {{- end }}

    {{- if .Values.ingress.hosts.hostconsole.enabled }}
    - host: {{ .Values.ingress.hosts.hostconsole.name | quote }}
      http:
        paths:
          {{- range .Values.ingress.hosts.hostconsole.paths }}
            {{- if or (not (hasKey . "enabled")) (eq .enabled true) }}
          - path: {{ .path }}
            pathType: ImplementationSpecific          
            backend:
              service:
                name: {{ $fullName }}-{{ .service }}
                port:
                  number: {{- if .servicePort }} {{ .servicePort }}{{- else }} {{ $svcPort }}{{- end }}                       
            {{- end }}
          {{- end }}
    {{- end }}

    {{- if .Values.ingress.hosts.hostapi.enabled }}
    - host: {{ .Values.ingress.hosts.hostapi.name | quote }}
      http:
        paths:
          {{- range .Values.ingress.hosts.hostapi.paths }}
          - path: {{ .path }}
            pathType: ImplementationSpecific          
            backend:
              service:
                name: {{ $fullName }}-{{ .service }}
                port:
                  number: {{- if .servicePort }} {{ .servicePort }}{{- else }} {{ $svcPort }}{{- end }}                       
          {{- end }}
    {{- end }}

    {{- if .Values.ingress.hosts.hostrtm.enabled }}
    - host: {{ .Values.ingress.hosts.hostrtm.name | quote }}
      http:
        paths:
          {{- range .Values.ingress.hosts.hostrtm.paths }}
          - path: {{ .path }}
            pathType: ImplementationSpecific          
            backend:
              service:
                name: {{ $fullName }}-{{ .service }}
                port:
                  number: {{- if .servicePort }} {{ .servicePort }}{{- else }} {{ $svcPort }}{{- end }}                       
          {{- end }}
    {{- end }}

    {{- if .Values.ingress.hosts.hostwidget.enabled }}
    - host: {{ .Values.ingress.hosts.hostwidget.name | quote }}
      http:
        paths:
          {{- range .Values.ingress.hosts.hostwidget.paths }}
          - path: {{ .path }}
            pathType: ImplementationSpecific          
            backend:
              service:
                name: {{ $fullName }}-{{ .service }}
                port:
                  number: {{- if .servicePort }} {{ .servicePort }}{{- else }} {{ $svcPort }}{{- end }}                       
          {{- end }}
    {{- end }}

{{- end }}
{{- end }}
